name: dad_jokes_demo
description: A demo Flutter projects with Dad jokes
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

  # Widgets
  badges: ^2.0.1

  # Utils
  vrouter: ^1.2.0+6
  dio: ^4.0.0
  country_code: ^1.0.0

  # Data
  shared_preferences: ^2.0.15
  shared_preferences_web: ^2.0.4
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  retrofit: ^3.3.1
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  provider: ^6.0.4
  url_launcher_web: ^2.0.13
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  freezed: ^2.3.0
  retrofit_generator: ^4.2.0
  lints: ^2.0.1

flutter:
  uses-material-design: true
